import {
  MockAnswer1,
  MockAnswer2,
  MockAnswer3,
  MockAnswer4,
} from "@/components/Answers/index";
import { Ticket } from "@/components/Ticket/index";

export const tickets2 = {
  TASK0948367: {
    id: "TASK0948367",
    sla: 2,
    priority: "3 - baixa",
    openedAt: "09/02/2024 17:15:47",
    updatedAt: "03/05/2024 14:34:26",
    status: "Em atendimento",
    resolvedAt: null,
    reportCategory: "Outros Sistemas",
    reportSubcategory: "Adapt",
    symptom: "Acesso a Relatórios",
    symptomQualification: "",
    assignmentGroup: "N2-LEG-SAT",
    category: "AMS-Não SAP",
    assignedTo: "Analista AMS",
    closedAt: "01/05/2024 18:00:04",
    taskRequester: "ADM Sistemas",
    location: "Fábrica 1",
    description: "Acesso a Relatórios",
    resolution: "Solução aplicada: Reiniciado serviço database",
    suggestions: [
      "Gerar documentação em pdf",
      "Como transferir um arquivo pela rede?",
      "Como criar novos Acessos?",
    ],
    messages: [
      <Ticket ticketId="TASK0948367" key={0} />,
      <MockAnswer1 key={1} />,
    ],
  },
  TASK0948362: {
    id: "TASK0948362",
    sla: 0,
    priority: 2,
    openedAt: "09/04/2024 17:15:47",
    updatedAt: "03/05/2024 14:34:26",
    reportStatus: "Em atendimento",
    resolvedAt: null,
    reportCategory: "Outros Sistemas",
    reportSubcategory: "Adapt",
    symptom: "Alteração de Acesso",
    symptomQualification: "",
    assignmentGroup: "N2-LEG-SAT",
    category: "AMS-Não SAP",
    assignedTo: "Analista AMS",
    closedAt: "01/05/2024 18:00:04",
    taskRequester: "ADM Sistemas",
    location: "Fábrica 1",
    description: "Alteração de Acesso",
    resolution: "Solução aplicada: Alteração de perfil",
    suggestions: [
      "Como realizar uma alteração de Acessos?",
      "Como criar novos Acessos?",
      "Impressora com problemas",
    ],
    messages: [
      <Ticket ticketId="TASK0948362" key={0} />,
      <MockAnswer2 key={1} />,
    ],
  },
  TASK0948364: {
    id: "TASK0948364",
    sla: 2,
    priority: 1,
    openedAt: "09/01/2024 17:15:47",
    updatedAt: "03/05/2024 14:34:26",
    reportStatus: "Resolvido",
    resolvedAt: null,
    reportCategory: "Outros Sistemas",
    reportSubcategory: "Adapt",
    symptom: "Reset de Senha",
    symptomQualification: "",
    assignmentGroup: "N2-LEG-SAT",
    category: "AMS-Não SAP",
    assignedTo: "Analista AMS",
    closedAt: "01/05/2024 18:00:04",
    taskRequester: "ADM Sistemas",
    location: "Fábrica 1",
    description: "Reset de Senha",
    resolution: "Solução aplicada: Resete de senha",
    messages: [
      <Ticket ticketId="TASK0948364" key={0} />,
      <MockAnswer3 key={1} />,
      "Obrigado, estou conseguindo aplicar os passos",
      "Não há de que! Estou aqui para ajudar :)",
    ],
  },

  TASK0948366: {
    id: "TASK0948366",
    sla: 2,
    priority: 3,
    openedAt: "09/02/2024 17:15:47",
    updatedAt: "03/05/2024 14:34:26",
    reportStatus: "Resolvido",
    resolvedAt: "03/05/2024 14:34:26",
    reportCategory: "Outros Sistemas",
    reportSubcategory: "Adapt",
    symptom: "Reset de Senha",
    symptomQualification: "",
    assignmentGroup: "N2-LEG-SAT",
    category: "AMS-Não SAP",
    assignedTo: "Analista AMS",
    closedAt: "01/05/2024 18:00:04",
    taskRequester: "ADM Sistemas",
    location: "Fábrica 1",
    description: "Reset de Senha",
    resolution: "Solução aplicada: Criação de menu novo",
    messages: [
      <Ticket ticketId="TASK0948366" key={0} />,
      "Ola",
      "Tudo certo?",
      "Também estou bem. Como posso te ajudar hoje?",
      "Estou tendo dificuldades, preciso resetar minha senha. Você pode me ajudar a abrir um chamado técnico?",
      <MockAnswer4 key={1} />,
    ],
  },
  TASK0340364: {
    id: "TASK0340364",
    sla: 2,
    priority: 2,
    openedAt: "09/02/2024 17:15:47",
    updatedAt: "03/05/2024 14:34:26",
    reportStatus: "Resolvido",
    resolvedAt: "03/05/2024 14:34:26",
    reportCategory: "Outros Sistemas",
    reportSubcategory: "Adapt",
    symptom: "Ativar Licença",
    symptomQualification: "",
    assignmentGroup: "N2-LEG-SAT",
    category: "AMS-Não SAP",
    assignedTo: "Analista AMS",
    closedAt: "01/05/2024 18:00:04",
    taskRequester: "ADM Sistemas",
    location: "Fábrica 1",
    description: "Ativar Licença",
    resolution: "Solução aplicada: Reiniciado serviço de database",
    messages: [
      <Ticket ticketId="TASK0340364" key={0} />,
      "Ola",
      "Tudo certo?",
      "Também estou bem. Como posso te ajudar hoje?",
      "Estou tendo dificuldades com o sistema e não consigo acessar o Office, o sistema apresenta senha expirada?",
      <MockAnswer4 key={1} />,
    ],
  },
};
